### ISSUE TITLE
Running on Docker Alpine

### ISSUE THREAD

**Issue by simon-tannai** [highcharts/highcharts-export-server#59]
Hi :)

I'm trying to run Highcharts export server on a light Docker container, based on Node.js image `8.11-alpine`.
But I'm confronted to error on pool workers:
```
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 1 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 2 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 3 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 4 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 1 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 2 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 3 is being written to, restart delayed
Mon Jun 18 2018 17:31:11 GMT+0000 (UTC) [warning] worker 4 is being written to, restart delayed
```

The workers are not starting up fine.

But from a non-alpine image, all is ok.

So, I imagine there is some Linux dependencies to install ? If yes, what are these dependencies ?

**Comment by vacas** [comment]
So, I've been having the same issue. This is what is run from the very beginning on the server of the app once I run `highcharts-export-server`:
```
Mon Jul 16 2018 23:56:59 GMT+0000 (UTC) [error] phantom worker 1 - { Error: spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/
phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  path: '/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  spawnargs:
   [ '/app/node_modules/highcharts-export-server/lib/../phantom/worker.js',
     '/app/node_modules/highcharts-export-server/lib/../' ] }
Mon Jul 16 2018 23:56:59 GMT+0000 (UTC) [warning] worker 1 is being written to, restart delayed
Mon Jul 16 2018 23:56:59 GMT+0000 (UTC) [error] phantom worker 2 - { Error: spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/
phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  path: '/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  spawnargs:
   [ '/app/node_modules/highcharts-export-server/lib/../phantom/worker.js',
     '/app/node_modules/highcharts-export-server/lib/../' ] }
Mon Jul 16 2018 23:56:59 GMT+0000 (UTC) [warning] worker 2 is being written to, restart delayed
```

And it keeps going on and on, infinite times.

Here is my `Dockerfile`:
```
FROM node:9.11-alpine

# build tools for native dependencies
RUN apk add --update make gcc g++ python git curl

ENV PKGNAME=graphicsmagick
ENV PKGVER=1.3.26
ENV PKGSOURCE=http://downloads.sourceforge.net/$PKGNAME/$PKGNAME/$PKGVER/GraphicsMagick-$PKGVER.tar.lz

# Installing graphicsmagick dependencies
RUN apk add --update lzip \
                     wget \
                     ffmpeg \
                     libjpeg-turbo-dev \
                     libpng-dev \
                     libtool \
                     libgomp && \
    wget $PKGSOURCE && \
    lzip -d -c GraphicsMagick-$PKGVER.tar.lz | tar -xvf - && \
    cd GraphicsMagick-$PKGVER && \
    ./configure \
      --build=$CBUILD \
      --host=$CHOST \
      --prefix=/usr \
      --sysconfdir=/etc \
      --mandir=/usr/share/man \
      --infodir=/usr/share/info \
      --localstatedir=/var \
      --enable-shared \
      --disable-static \
      --with-modules \
      --with-threads \
      --with-gs-font-dir=/usr/share/fonts/Type1 \
      --with-quantum-depth=16 && \
    make && \
    make install && \
    cd / && \
    rm -rf GraphicsMagick-$PKGVER && \
    rm GraphicsMagick-$PKGVER.tar.lz

RUN apk add --update py-pip unzip

RUN mkdir -p /app
COPY package.json /app

WORKDIR /app

RUN npm install

COPY . /app

ENV API_SERVER=https://api.floodiq.com
ENV SHARE_SERVER=https://b.floodiq.com/share/
ARG MONGO_HOST=mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/datas
ENV MONGO_HOST ${MONGO_HOST}
ARG PORT=80
ENV PORT ${PORT}

EXPOSE 80
CMD ["npm", "start"]
```

I've tried a few solutions I've found online, such as changing the version to `8.11-alpine`, `8.7-alpine` or `8.7-wheezy`, `npm rebuild phantomjs-prebuilt`, installing phantomjs globally, locally, using curl... you name it, pretty much done it.

I honestly feel this might be more a Docker issue or PhantomJS issue, but coming here for a potential solution. Any potential solutions?

**Comment by niketh** [comment]
Was anyone able to get this working? I am facing the same issue

**Comment by vacas** [comment]
So, there were some updates to Dockerfile on my side:

1. Changed to `FROM node:10.7.0-alpine`
2. Added `ENV ACCEPT_HIGHCHARTS_LICENSE="YES"`
3. Added `RUN curl -Ls "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C /` after the graphicsmagick dependencies installation command
4. Added `COPY .npmrc /app` after making the `/app` dir

Also added an `.npmrc` file, and inside it, added `phantomjs_cdnurl=https://cnpmjs.org/downloads`

These additions ended up working on our server. 

Let me know if it helps.

**Comment by asafel** [comment]
@vacas 
I'm having the same issue now.
Unfortunately none of the above is helping.

I tried so many things.

Maybe you have and more cards in your sleeve?

**Comment by pierregangloff** [comment]
Hi drmrbrewer, would you mind sharing your Dockerfile. I'm going insane trying to find an O/S, node, phantomjs combination that works to Dockerize this thing. I've tried so many versions of node, it's not even funny anymore. Issues I ran into:
- PhantomJS: SyntaxError: Unexpected token < in JSON at position 0
- Highcharts-export-server error on statup: [warning] worker 2 is being written to, restart delayed (this even happens on my Ubuntu 20.04, not even when trying to dockerize)
- Phantom installation failed { [Error: EACCES: permission denied, link 
- phantom worker 2 unexpected data - SyntaxError: Expected token ')'

I've tried the 5+ years old dockerized version of highcharts-export-server from onsdigital (1M+ pulls) at https://hub.docker.com/r/onsdigital/highcharts-export-node/
... but that one is old and has a zillion security vulnerabilities. Well, PhantomJS has a ton too. So, I don't want to Node 7.7... I've tried so many things but I need to get this to work to replace some infrastructure and until we can get rid of this security-issues-laced product which just won't run... I'm hoping to run it in a newer version of some O/S, node, PhantomJS, highcharts combination. But given that you have a Dockerfile working, I'd love to get my eyes on that so that I do something similar. For now, I'll follow your lead and start from ubuntu 20.04 (latest, that's already great news), then install latest node on that, and then try to get highcharts-export-server working on that (but I have a feeling I might need to manually install an older version of PhantomJS first).

This is soooo frustrating, this is not how code should be done (just picking up whatever's latest to make it impossible to know what combinations actually work, this is totally underterministic builds, yuck!). I must've wasted 3 days trying to get this to work. Playing try and fail for 3 days, that's not good software engineering... I hope the refactored code will have more deterministic builds. No package.json ^ carret versions, no simply npm install whatever's latest. I hope they put specific version so that we can build the exact same thing....

Thanks so much in advance. Your Dockerfile will save me from all this export server insanity/dependency hell.

**Comment by drmrbrewer** [comment]
I feel your pain!

My Dockerfile has lots of stuff that is slightly messy and specific to my use-case... the following are the bits that I think are relevant:

	FROM ubuntu:20.04

	ENV DEBIAN_FRONTEND=noninteractive

	# Install build dependencies...
	RUN apt-get update && apt install -y build-essential curl git \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*

	# Install node.js...
	RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
	RUN apt-get update && apt-get install -y nodejs \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*

	# Install phantomjs into the container...
	# Install runtime dependencies...
	RUN apt-get update \
	 && apt-get install -y --no-install-recommends \
			ca-certificates \
			bzip2 \
			libfontconfig \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*
	# Install official PhantomJS release...
	RUN set -x  \
	 && apt-get update \
	 && apt-get install -y --no-install-recommends \
			curl \
	 && mkdir /tmp/phantomjs \
	 && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
			| tar -xj --strip-components=1 -C /tmp/phantomjs \
	 && mv /tmp/phantomjs/bin/phantomjs /usr/local/bin \
	 && apt-get purge --auto-remove -y \
			curl \
	 && apt-get clean \
	 && rm -rf /tmp/* /var/lib/apt/lists/*

Regarding `Unexpected token < in JSON at position 0` I think that this might result from some stuff (starting with `<`) being dumped by your worker to `stdout`.  But I admit that I haven't delved into the murky depths of this code so I don't recall the details... I just know that if I inadvertently leave any `console.log()` statements in the code that is executed by the worker then this will result in an error like that.

**Comment by pierregangloff** [comment]
Here's my Dockerfile. It almost works but when I make a sample request, it bombs:

```
FROM ubuntu:20.04

# update/upgrade ubuntu, install curl, install node
RUN apt-get update \
    && apt-get upgrade \
    && apt-get -y install libfontconfig \
    && apt-get -y install curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_16.x  | bash - \
    && apt-get -y install nodejs

ENV ACCEPT_HIGHCHARTS_LICENSE="YES"

# see available versions of highcharts at https://www.npmjs.com/package/highcharts-export-server
# Bad: (should always be deterministic=should always specify a version!)
#   RUN npm install highcharts-export-server -g
# Better:
RUN npm install highcharts-export-server@2.0.30 -g

EXPOSE 9000

# run the container using: docker run -p 9000:9000 -t CONTAINER_TAG
ENTRYPOINT ["highcharts-export-server", "--enableServer", "1", "--port", "9000"]
```

I can then send this sample request:

` curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' localhost:9000 -o testchartasdasd2asd.png`

But highcharts-export-server bombs out (both the latest and 2.0.30):

```
    __  ___       __         __               __
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/
        ____//___/                  __     _____
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/
              /_/

                                                                  v2.1.0
Thu Nov 04 2021 17:54:38 GMT+0000 (Coordinated Universal Time) [error] phantom worker 2 unexpected data - SyntaxError: Expected token ')'

  phantomjs://code/worker.js:658 in loop
{"data":"iVBORw0KGgoAAAANSUhE
```

 This is where I'm back to trying different versions of node, highcharts, phantomjs, etc. And where you come in, if you have a working Dockerfile, you would save my life :)

**Comment by pierregangloff** [comment]
I'm trying your dockerfile now, THANK YOU SOOOO MUCH!!!!

**Comment by drmrbrewer** [comment]
I should add that I'm not really using the export server as a whole, I'm just taking the worker/pool part of it and shoe-horning it into my existing server environment, so my experience (and Dockerfile) may not be entirely applicable to your situation.

**Comment by pierregangloff** [comment]
ahhh ok, here's where I end up: I copied your steps and bundled them up into a single docker layer, like this:

```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# update/upgrade ubuntu,
# install dependencies: build-essential curl gnupg (for this Dockerfile),
# install dependencies: libfontconfig ca-certificates bzip2 (for Phantomjs),
# install curl,
# install node,
# install phantomjs,
# cleanup apt-get and its lists
RUN apt-get update \
    && apt-get upgrade \
    && apt-get -y install build-essential curl gnupg libfontconfig ca-certificates bzip2 \
    && curl -sL https://deb.nodesource.com/setup_16.x  | bash - \
    && apt-get -y install nodejs \
    && set -x  \
    && apt-get update \
    && mkdir /tmp/phantomjs \
    && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    		| tar -xj --strip-components=1 -C /tmp/phantomjs \
    && mv /tmp/phantomjs/bin/phantomjs /usr/local/bin \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/*

ENV ACCEPT_HIGHCHARTS_LICENSE="YES"

# see available versions of highcharts at https://www.npmjs.com/package/highcharts-export-server
# Bad: (should always be deterministic=should always specify a version!)
#   RUN npm install highcharts-export-server -g
# Better:
RUN npm install highcharts-export-server@2.0.30 -g

EXPOSE 9000

# run the container using: docker run -p 9000:9000 -t CONTAINER_TAG
ENTRYPOINT ["highcharts-export-server", "--enableServer", "1", "--port", "9000"]
```

I then tested it with the same input as before (this input works fine with the 5-year-old onsdigital docker container on dockerhub, so I  know this input should work:

```
curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' localhost:9000 -o testchartasdasd2asd.png
```

But I end up with an error, like before. Seems like I'm not too far off but this is so painful, it's still not working:

```
docker run -p 9000:9000 hc:9
    __  ___       __         __               __
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/
        ____//___/                  __     _____
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/
              /_/

                                                                  v2.0.30
Thu Nov 04 2021 18:37:00 GMT+0000 (Coordinated Universal Time) [error] phantom worker 4 unexpected data - SyntaxError: Expected token ')'

  phantomjs://code/worker.js:628 in loop
{"data":"iVBORw0KGgoAAAANSUhEUgAAAlgA
...snip...
rn0iHJBjt7QAAAABJRU5ErkJggg=="} {
  data: {
    width: false,
    callback: false,
    resources: false,
    scale: 1,
    constr: undefined,
    chart: {
      title: [Object],
      xAxis: [Object],
      series: [Array],
      chart: [Object],
      exporting: [Object]
    },
    svgstr: undefined,
    format: 'png',
    out: 'tmp/chart.5d43bc9f85a84a39882e01d5c2e9c8dc.png',
    styledMode: false,
    asyncRendering: false,
    async: false,
    reqID: '5d43bc9f85a84a39882e01d5c2e9c8dc',
    globalOptions: false,
    themeOptions: 'false',
    customCode: false,
    dataOptions: false,
    id: 4
  },
  working: true,
  ready: false,
  alive: true,
  process: <ref *1> ChildProcess {
    _events: [Object: null prototype] {
      uncaughtException: [Function (anonymous)],
      error: [Function (anonymous)],
      close: [Function (anonymous)]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 0,
    connected: false,
    signalCode: null,
    exitCode: null,
    killed: false,
    spawnfile: '/usr/local/bin/phantomjs',
    _handle: Process {
      onexit: [Function (anonymous)],
      pid: 16,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    spawnargs: [
      '/usr/local/bin/phantomjs',
      '/usr/lib/node_modules/highcharts-export-server/lib/../phantom/worker.js',
      '/usr/lib/node_modules/highcharts-export-server/lib/../'
    ],
    pid: 16,
    stdin: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(async_id_symbol)]: 28,
      [Symbol(kHandle)]: [Pipe],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdout: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(async_id_symbol)]: 29,
      [Symbol(kHandle)]: [Pipe],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stderr: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(async_id_symbol)]: 30,
      [Symbol(kHandle)]: [Pipe],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdio: [ [Socket], [Socket], [Socket] ],
    [Symbol(kCapture)]: false
  },
  workStartTime: 1636051018141,
  ondone: [Function (anonymous)],
  workcount: 8,
  incoming: "SyntaxError: Expected token ')'\n" +
    '\n' +
    '  phantomjs://code/worker.js:628 in loop\n' +
    '{"data":"iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAY
```

So, for now, I'll use the 5-year-old docker container from dockerhub and will hope that someone will see this and make sense of the above error so that I can run a more recent/secure OS/nodejs/etc version :(

Thanks again for the help @drmrbrewer !!

Pierre

```

**Comment by bigbadbob2003** [comment]
I managed to get a working ubuntu version with the following

```
FROM ubuntu:latest
ENV ACCEPT_HIGHCHARTS_LICENSE=1
ENV HIGHCHARTS_VERSION=9.2.2
ENV HIGHCHARTS_USE_STYLED=0
EXPOSE 7801
WORKDIR /app

RUN apt-get update \
    && apt-get upgrade \
    && apt-get -y install libfontconfig \
    && apt-get -y install curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_15.x  | bash - \
    && apt-get -y install nodejs \
    && apt-get -y install git

RUN git clone https://github.com/highcharts/node-export-server
RUN cd node-export-server && npm install && npm link

ENTRYPOINT [ "highcharts-export-server",  "--enableServer", "1", "--host", "0.0.0.0"]
```

The important part was the HIGHCHARTS_VERSION and the Node version 15.x
